const domainLabels = {
  race: 'Race Compendium',
  class: 'Class Compendium',
  creature: 'Creature Compendium',
  item: 'Item Compendium',
  spell: 'Spell Compendium',
  talent: 'Talent Compendium',
  profession: 'Profession Compendium',
  skill: 'Skill Compendium',
  origin: 'Origin Compendium',
  location: 'Location Compendium',
  religion: 'Theology Compendium',
  faction: 'Faction Compendium',
  lore: 'Lore Compendium',
  handbook: 'Asteria Handbook'
};

const workspaceSections = {
  race: 'Races',
  class: 'Classes',
  creature: 'Creatures',
  item: 'Items',
  spell: 'Magic',
  talent: 'Classes',
  profession: 'Asteria Handbook',
  skill: 'Skills',
  origin: 'Asteria Handbook',
  location: 'World, Realms & Planes',
  religion: 'Theology',
  faction: 'Factions',
  lore: 'Asteria Handbook',
  handbook: 'Asteria Handbook'
};

const tabTemplates = {
  race: ['Overview','Racial Sheet','Lore','Culture','Historical Figures','Settlements','Relations','Traits & Biology','Gallery','GM Notes'],
  class: ['Overview','Talent Tree','Lore','Gallery','GM Notes'],
  creature: ['Overview','Stat Sheet','Lore','Habitat','Behaviour','Combat','Loot & Drops','Soul Information','Variants','Encounter Use','Gallery','GM Notes'],
  item: ['Overview','Properties','Crafting','Lore','Sources','Gallery','GM Notes'],
  spell: ['Overview','Casting','Scaling','Lore','Sources','GM Notes'],
  talent: ['Overview','Ranks','Prerequisites','Scaling','Synergy','GM Notes'],
  profession: ['Overview','Progression','Tools','Recipes','Lore','GM Notes'],
  skill: ['Overview','Ranks','Checks','Training','Lore','GM Notes'],
  origin: ['Overview','Background','Family','Story Hooks','Lore','GM Notes'],
  location: ['Overview','Map Notes','Regions','Factions','Lore','Encounters','GM Notes'],
  religion: ['Overview','Domains','Worship','Lore','Followers','Rituals','GM Notes'],
  faction: ['Overview','Influence','Members','Relations','Holdings','History','Hooks','GM Notes'],
  lore: ['Overview','Chronicle','People','Places','Artifacts','Related','GM Notes'],
  handbook: ['Overview','Rules','Examples','Related','GM Notes']
};

const sharedFilterKeys = [
  'category',
  'rarity',
  'role',
  'size',
  'biome',
  'habitat',
  'region',
  'faction',
  'pantheon',
  'deity',
  'divineDomain',
  'spellSchool',
  'element',
  'damageType',
  'castingType',
  'rank',
  'talentTier',
  'professionType',
  'skillRank',
  'locationType',
  'settlementType',
  'alignment',
  'availability',
  'playable',
  'climate',
  'language',
  'threatTier',
  'levelRange',
  'magicType',
  'essenceAffinity',
  'loreStatus',
  'status',
  'visibility'
];

const domainFilterFields = {
  race: ['category','region','essenceAffinity','size','playable','language','loreStatus','visibility'],
  class: ['category','role','magicType','difficulty','primaryStat','secondaryStat','availability','visibility'],
  creature: ['category','threatTier','levelRange','size','biome','habitat','hostility','magical','boss','soulTier','encounterRole','visibility'],
  item: ['category','collection','rarity','itemType','craftingCategory','materialType','affinity','source','visibility'],
  spell: ['category','spellSchool','magicType','element','damageType','castingType','rank','visibility'],
  talent: ['category','talentTier','role','primaryStat','className','rank','visibility'],
  profession: ['category','professionType','toolType','craftingCategory','region','rank','visibility'],
  skill: ['category','skillRank','primaryStat','trainingType','visibility'],
  origin: ['category','region','faction','status','visibility'],
  location: ['category','locationType','region','biome','climate','faction','settlementType','visibility'],
  religion: ['category','pantheon','deity','divineDomain','alignment','region','visibility'],
  faction: ['category','factionType','region','alignment','influence','status','visibility'],
  lore: ['category','era','region','faction','loreStatus','visibility'],
  handbook: ['category','status','visibility']
};

const databaseDefinitions = Object.fromEntries(Object.keys(domainLabels).map(domain => [domain, {
  domain,
  label: domainLabels[domain],
  workspaceSection: workspaceSections[domain] || workspaceSections.handbook,
  roots: ['content'],
  routeBase: `/compendium/${domain}`,
  tabs: tabTemplates[domain] || tabTemplates.handbook,
  filterFields: domainFilterFields[domain] || sharedFilterKeys,
  visibilityLevels: ['public','player','gm-only']
}]));

const filterAliases = {
  rarity: ['itemClass','item_class','rarity'],
  itemType: ['itemType','item_type'],
  craftingCategory: ['craftingCategory','crafting_category','category'],
  materialType: ['materialType','material_type'],
  source: ['source','sourcebook','originSource','origin_source'],
  role: ['role','partyRole','party_role','encounterRole','encounter_role'],
  size: ['size'],
  biome: ['biome','biomes'],
  habitat: ['habitat','habitats'],
  region: ['region','regions'],
  faction: ['faction','factions','relatedFactions','related_factions'],
  pantheon: ['pantheon','pantheons'],
  deity: ['deity','god','gods'],
  divineDomain: ['divineDomain','divine_domain','domains'],
  spellSchool: ['spellSchool','spell_school','school','magicSchool','magic_school'],
  element: ['element','elements','affinity','affinities'],
  damageType: ['damageType','damage_type'],
  castingType: ['castingType','casting_type'],
  rank: ['rank','spellRank','spell_rank'],
  talentTier: ['talentTier','talent_tier','tier'],
  professionType: ['professionType','profession_type'],
  skillRank: ['skillRank','skill_rank','rank'],
  locationType: ['locationType','location_type'],
  settlementType: ['settlementType','settlement_type'],
  factionType: ['factionType','faction_type'],
  alignment: ['alignment'],
  influence: ['influence','influenceLevel','influence_level'],
  era: ['era','age','timeline'],
  availability: ['availability','playable'],
  playable: ['playable'],
  climate: ['climate'],
  language: ['language','languages'],
  threatTier: ['threatTier','threat_tier'],
  levelRange: ['levelRange','level_range'],
  hostility: ['hostility'],
  magical: ['magical'],
  boss: ['boss'],
  soulTier: ['soulTier','soul_tier'],
  encounterRole: ['encounterRole','encounter_role'],
  magicType: ['magicType','magic_type'],
  essenceAffinity: ['essenceAffinity','essence_affinity','affinity','affinities'],
  primaryStat: ['primaryStat','primary_stat'],
  secondaryStat: ['secondaryStat','secondary_stat'],
  className: ['className','class_name','class'],
  difficulty: ['difficulty'],
  toolType: ['toolType','tool_type'],
  trainingType: ['trainingType','training_type'],
  loreStatus: ['loreStatus','lore_status','loreVisibility','lore_visibility'],
  status: ['status'],
  visibility: ['visibility']
};


module.exports = { domainLabels, workspaceSections, tabTemplates, domainFilterFields, filterAliases, databaseDefinitions };
