import React, { useState } from 'react';
import { Panel, EmptyState, Tabs, StatusPill } from '../components/WorkspaceUI.jsx';
import { informationScopes } from '../state/campaignInformation.mjs';
import { firebaseService } from '../firebase/asteriaFirebaseService.js';
import { useAsyncAction } from '../components/useAsyncAction.js';
const blank=campaign=>({id:`info-${crypto.randomUUID()}`,title:'',description:'',scope:informationScopes(campaign)[0]?.scope || 'World',location:informationScopes(campaign)[0]?.location || '',source:'',start:'',end:'',status:'Upcoming',published:false});
export function InformationCard({entry,children}) {
  return <article className="react-information-card"><header><h3>{entry.title || entry.name}</h3>{entry.kind==='events'?<StatusPill>{entry.status}</StatusPill>:null}</header><p className="react-help">{entry.scope}{entry.location?` · ${entry.location}`:''}{entry.source?` · ${entry.source}`:''}</p><p className="react-information-copy">{entry.description || entry.note}</p>{entry.start || entry.end?<p>{entry.start?`Starts: ${entry.start}`:''}{entry.end?` · Ends: ${entry.end}`:''}</p>:null}{children}</article>;
}
export function CampaignInformationWorkspace({campaignId,campaign,workspace,characters}) {
  const [kind,setKind]=useState('news'),[draft,setDraft]=useState(()=>blank(campaign));
  const [target,setTarget]=useState(''),[title,setTitle]=useState(''),[message,setMessage]=useState('');
  const action=useAsyncAction(),records=workspace.world?.[kind] || [],scopes=informationScopes(campaign);
  const save=async()=>{const result=await action.run(()=>firebaseService.saveInformation(campaignId,kind,draft),draft.published?'Published to the campaign.':'Draft saved.');if(result?.ok)setDraft(blank(campaign));};
  return <div className="react-information-workspace"><Panel title="Campaign Information"><Tabs tabs={[{id:'news',label:'News'},{id:'events',label:'Events'}]} active={kind} onChange={value=>{setKind(value);setDraft(blank(campaign));}} ariaLabel="Information type"/>
    <div className="react-form-grid"><label>Title<input maxLength={160} value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/></label><label>Scope<select value={draft.scope} onChange={e=>setDraft(d=>({...d,scope:e.target.value,location:scopes.find(s=>s.scope===e.target.value)?.location || ''}))}>{scopes.map(s=><option key={s.scope}>{s.scope}</option>)}</select></label><label>Location<input maxLength={160} value={draft.location} onChange={e=>setDraft(d=>({...d,location:e.target.value}))}/></label></div>
    <label>Description<textarea rows="5" maxLength={12000} value={draft.description} onChange={e=>setDraft(d=>({...d,description:e.target.value}))}/></label>
    {kind==='news'?<label>Source<input maxLength={160} placeholder="Newspaper, town crier, rumour…" value={draft.source} onChange={e=>setDraft(d=>({...d,source:e.target.value}))}/></label>:<div className="react-form-grid"><label>Status<select value={draft.status} onChange={e=>setDraft(d=>({...d,status:e.target.value}))}>{['Upcoming','Ongoing','Completed','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></label>{[['start','In-world start (optional)'],['end','In-world end (optional)']].map(([key,label])=><label key={key}>{label}<input maxLength={200} value={draft[key]} onChange={e=>setDraft(d=>({...d,[key]:e.target.value}))}/></label>)}</div>}
    <label><input type="checkbox" checked={draft.published} onChange={e=>setDraft(d=>({...d,published:e.target.checked}))}/>Published to players in this campaign</label>
    <div className="react-action-row"><button className="primary" disabled={action.busy||!draft.title.trim()} onClick={save}>{draft.published?'Save & Publish':'Save Draft'}</button><button disabled={action.busy} onClick={()=>setDraft(blank(campaign))}>New Entry</button></div><p role="status">{action.message}</p>
    {records.map(entry=><InformationCard key={entry.id} entry={{...entry,kind}}><StatusPill>{entry.published?'Published':'Draft'}</StatusPill><button disabled={action.busy} onClick={()=>setDraft({...blank(campaign),...entry,title:entry.title||entry.name||'',description:entry.description||entry.note||'',status:kind==='events'&&['Upcoming','Ongoing','Completed','Cancelled'].includes(entry.status)?entry.status:'Upcoming'})}>Edit</button></InformationCard>)}{!records.length?<EmptyState title={`No ${kind} yet`}/>:null}
  </Panel><Panel title="Send Player Notification"><label>Character<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose a character</option>{Object.values(characters).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Title<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)}/></label><label>Message<textarea value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)}/></label><button disabled={action.busy||!target||!title.trim()||!message.trim()} onClick={async()=>{const result=await action.run(()=>firebaseService.sendNotification(campaignId,target,{title,message}),'Notification sent.');if(result?.ok){setTitle('');setMessage('');}}}>Send Notification</button></Panel></div>;
}
